Improve the release process

diff --git a/.github/workflows/build_kernel.yml b/.github/workflows/build_kernel.yml
--- a/.github/workflows/build_kernel.yml
+++ b/.github/workflows/build_kernel.yml
@@ -51,6 +51,23 @@ jobs:
         run: |
           echo "${CLANG_PATH}" >> $GITHUB_PATH
 
+      - name: Extract kernel version from Makefile
+        run: |
+          MAKEFILE_PATH="${{ github.workspace }}/kernel/Makefile"
+          if [ -f "$MAKEFILE_PATH" ]; then
+            KERNEL_VERSION=$(grep "^VERSION" "$MAKEFILE_PATH" | awk '{print $3}')
+            KERNEL_PATCHLEVEL=$(grep "^PATCHLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
+            KERNEL_SUBLEVEL=$(grep "^SUBLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
+            FULL_KERNEL_VERSION="${KERNEL_VERSION}.${KERNEL_PATCHLEVEL}.${KERNEL_SUBLEVEL}"
+            echo "KERNEL_VERSION=${FULL_KERNEL_VERSION}" >> $GITHUB_ENV
+          else
+            echo "Makefile not found in the kernel directory of the GitHub workspace. Contents of the kernel directory:" >&2
+            ls -R "${{ github.workspace }}/kernel"
+          fi
+
+      - name: Extract sources
+        run: bash ExSource.sh
+        
       - name: Compile kernel
         run: |
           chmod +x build.sh
@@ -108,27 +125,34 @@ jobs:
           chmod +x makezip.sh
           ./makezip.sh
 
-      - name: List files for testing
-        run: |
-          ls -l
-
       - name: Make a release
         uses: softprops/action-gh-release@v1
         with:
           files: |
-            ${{ github.workspace }}/${{ env.ZIP_NO_KSU }}
-            ${{ github.workspace }}/${{ env.ZIP_KSU }}
+             ${{ github.workspace }}/${{ env.ZIP_NO_KSU }}
+             ${{ github.workspace }}/${{ env.ZIP_KSU }}
           token: ${{ secrets.GITHUB_TOKEN }}
-          release_name: ${{ github.event.inputs.version }}-${{ env.KERNELSU_VERSION }}
+          name: Realme 8 (nashc) Kernel Release - ${{ env.KERNELSU_VERSION }}
+          tag_name: ${{ github.run_id }}
           body: |
-            This is a release for ${{ github.event.inputs.version }}-${{ env.KERNELSU_VERSION }}.
-            - With and without KernelSU support
-            - Flash in recovery 
-            - Warning flashing zip while using realmeUI will cause bootloop
-            Build settings used:
-            ```
-            ${{ env.JSON_CONTENTS }}
-            ```
-          tag: ${{ github.event.inputs.version }}-${{ github.sha }}
+             **Info:**
+              - KernelSU Version: ${{ env.KERNELSU_VERSION }}.
+              - Kernel Versions:
+                - LineageOS-20: ${{ env.KERNEL_VERSION }}
+                - Zenitsu: ${{ env.KERNEL_VERSION }}
+      
+             **Source URLs:**
+             - LineageOS-20: ${{ env.lineage_url }}
+             - Zenitsu: ${{ env.zenitsu_url }}
+      
+             **Installation:**
+             1. Sideloading in recovery mode.
+             2. Refer to our [Mega Guide](https://github.com/driedpampas/realme-8-megaguide) for detailed instructions.
+      
+             **Warnings:**
+             - Do not use this kernel with the stock firmware of Realme UI; it is only compatible with custom ROMs.
+      
+             **Support Group:**
+             - Support: Ask In [Realme 8 AOSP](https://t.me/Realme8AOSPGroup) for assistance
           draft: false
           prerelease: false
