[Stable] Final Merge

diff --git a/.github/workflows/build_kernel.yml b/.github/workflows/build_kernel.yml
--- a/.github/workflows/build_kernel.yml
+++ b/.github/workflows/build_kernel.yml
@@ -1,4 +1,4 @@
-name: KernelSU Builder
+name: Kernel Builder
 
 on:
   push:
@@ -51,6 +51,20 @@ jobs:
       - name: Add Clang to PATH
         run: |
           echo "${CLANG_PATH}" >> $GITHUB_PATH
+
+      - name: Extract kernel version from Makefile
+        run: |
+          MAKEFILE_PATH="${{ github.workspace }}/kernel/Makefile"
+          if [ -f "$MAKEFILE_PATH" ]; then
+          KERNEL_VERSION=$(grep "^VERSION" "$MAKEFILE_PATH" | awk '{print $3}')
+          KERNEL_PATCHLEVEL=$(grep "^PATCHLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
+          KERNEL_SUBLEVEL=$(grep "^SUBLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
+          FULL_KERNEL_VERSION="${KERNEL_VERSION}.${KERNEL_PATCHLEVEL}.${KERNEL_SUBLEVEL}"
+          echo "KERNEL_VERSION=${FULL_KERNEL_VERSION}" >> $GITHUB_ENV
+          else
+          echo "Makefile not found in the kernel directory of the GitHub workspace. Contents of the kernel directory:" >&2
+           ls -R "${{ github.workspace }}/kernel"
+          fi
 
       - name: Compile kernel
         run: |
@@ -125,12 +139,15 @@ jobs:
           body: |
              **Info:**
               - KernelSU Version: ${{ env.KERNELSU_VERSION }}.
+              - Kernel Versions:
+                - LineageOS-20: ${{ env.KERNEL_VERSION }}
+                - Zenitsu: ${{ env.KERNEL_VERSION }}
       
              **Installation:**
              1. Sideloading in recovery mode.
              2. Refer to our [Mega Guide](https://github.com/driedpampas/realme-8-megaguide) for detailed instructions.
       
-              **Warnings:**
+             **Warnings:**
              - Do not use this kernel with the stock firmware of Realme UI; it is only compatible with custom ROMs.
       
              **Support Group:**
