Add More info

diff --git a/.github/workflows/build_kernel.yml b/.github/workflows/build_kernel.yml
--- a/.github/workflows/build_kernel.yml
+++ b/.github/workflows/build_kernel.yml
@@ -56,15 +56,21 @@ jobs:
         run: |
           MAKEFILE_PATH="${{ github.workspace }}/kernel/Makefile"
           if [ -f "$MAKEFILE_PATH" ]; then
-          KERNEL_VERSION=$(grep "^VERSION" "$MAKEFILE_PATH" | awk '{print $3}')
-          KERNEL_PATCHLEVEL=$(grep "^PATCHLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
-          KERNEL_SUBLEVEL=$(grep "^SUBLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
-          FULL_KERNEL_VERSION="${KERNEL_VERSION}.${KERNEL_PATCHLEVEL}.${KERNEL_SUBLEVEL}"
-          echo "KERNEL_VERSION=${FULL_KERNEL_VERSION}" >> $GITHUB_ENV
+            KERNEL_VERSION=$(grep "^VERSION" "$MAKEFILE_PATH" | awk '{print $3}')
+            KERNEL_PATCHLEVEL=$(grep "^PATCHLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
+            KERNEL_SUBLEVEL=$(grep "^SUBLEVEL" "$MAKEFILE_PATH" | awk '{print $3}')
+            FULL_KERNEL_VERSION="${KERNEL_VERSION}.${KERNEL_PATCHLEVEL}.${KERNEL_SUBLEVEL}"
+            echo "KERNEL_VERSION=${FULL_KERNEL_VERSION}" >> $GITHUB_ENV
           else
-          echo "Makefile not found in the kernel directory of the GitHub workspace. Contents of the kernel directory:" >&2
-           ls -R "${{ github.workspace }}/kernel"
+            echo "Makefile not found in the kernel directory of the GitHub workspace. Contents of the kernel directory:" >&2
+            ls -R "${{ github.workspace }}/kernel"
           fi
+
+      - name: Extract source URLs
+        id: extract_sources
+        run: |
+          echo "::set-output name=lineage_url::$(yq e '.LineageOS-20.kernel[0]' sources.yml)"
+          echo "::set-output name=zenitsu_url::$(yq e '.Zenitsu.kernel[0]' sources.yml)"
 
       - name: Compile kernel
         run: |
@@ -123,10 +129,6 @@ jobs:
           chmod +x makezip.sh
           ./makezip.sh
 
-      - name: List files for testing
-        run: |
-          ls -l
-
       - name: Make a release
         uses: softprops/action-gh-release@v1
         with:
@@ -142,6 +144,10 @@ jobs:
               - Kernel Versions:
                 - LineageOS-20: ${{ env.KERNEL_VERSION }}
                 - Zenitsu: ${{ env.KERNEL_VERSION }}
+      
+             **Source URLs:**
+             - LineageOS-20: ${{ steps.extract_sources.outputs.lineage_url }}
+             - Zenitsu: ${{ steps.extract_sources.outputs.zenitsu_url }}
       
              **Installation:**
              1. Sideloading in recovery mode.
